{
 "title": "Kafka Consumer Group",
 "tags": [
  "kafka",
  "kpow",
  "consumer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(group_offset_lag, env)"
   },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": "label_values(group_offset_lag{env=~\"$env\"}, target)"
   }
  ]
 },
 "panels": [
  { "title": "Summary Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Groups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(count by (target) (group_offset_lag{env=~\"$env\", target=~\"$consumer_group\"}))"
    }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(group_member_count{env=~\"$env\", target=~\"$consumer_group\"})"
    }
   ]
  },
  {
   "title": "Assignments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(group_assignment_count{env=~\"$env\", target=~\"$consumer_group\"})"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(group_host_count{env=~\"$env\", target=~\"$consumer_group\"})"
    }
   ]
  },
  {
   "title": "Total Lag",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(group_offset_lag{env=~\"$env\", target=~\"$consumer_group\"})"
    }
   ]
  },
  {
   "title": "Read/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(group_offset_delta{env=~\"$env\", target=~\"$consumer_group\"})"
    }
   ]
  },
  { "title": "Performance Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Lag Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group_offset_lag{env=~\"$env\", target=~\"$consumer_group\"}",
     "legendFormat": "{{target}} ({{quantile}})"
    }
   ]
  },
  {
   "title": "Consumption Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "msgr/s" } },
   "targets": [
    {
     "expr": "group_offset_delta{env=~\"$env\", target=~\"$consumer_group\"}",
     "legendFormat": "{{target}} ({{quantile}})"
    }
   ]
  },
  { "title": "Detailed Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Consumer Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "group_state{env=~\"$env\", target=~\"$consumer_group\"}"
    }
   ]
  }
 ]
}